/**389. Find the Difference
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 */

class Solution {
    public char findTheDifference(String s, String t) {
        int k = 0;
        int j = 0;
        for (int i = 0; i<s.length(); i++){
            k+=s.charAt(i);
            j+=t.charAt(i);
        }
        j+=t.charAt(s.length());
        return (char) (j-k);
    }
}